name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build essentials (if needed)
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Compile main program
      run: make

    - name: Compile and run tests
      run: make test
